### ISSUE TITLE
Mailscout on CLI consoles (ie. Command Prompt)

### ISSUE THREAD

**Issue by JAnon-dot-gov** [batuhanaky/mailscout#3]
how do I run Mailscout on CLIs like Command Prompt? currently using W10 right now

-Jae

**Comment by batuhanaky** [comment]
Hey,

Mailscout doesn't have a CLI script for now, but it is possible for you to simply use the provided modules to put together a simple CLI interface.

 I'm planning to give an update in the near future as we have a growing user base, and include a CLI script within my update.

If you ever write one for yourself, feel free to share it with us :)

**Comment by batuhanaky** [comment]
I am marking the issue as solved but you're welcome if you want to open another issue.
